[build]
builder = "nixpacks"
buildCommand = "bundle install && bundle exec rails assets:precompile"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec puma -C config/puma.rb"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
